### ISSUE TITLE
Problem on Ubuntu 14.04

### ISSUE THREAD

**Issue by pathet** [Graylog2/fpm-recipes#48]
Hi,

i get this messages after starting the collector service.

2015-09-08T15:15:59.128+0200 INFO  [main] cli.commands.Run - Starting Collector v0.4.1 (commit 36a0856)
2015-09-08T15:15:59.131+0200 INFO  [main] cli.commands.Run - Running on Ubuntu 14.04.1 LTS (trusty) Linux 3.13.0-32-generic (amd64)
2015-09-08T15:16:00.030+0200 INFO  [main] collector.utils.CollectorId - No node ID file found. Generated: 1c5f10d4-2190-47c6-88f4-0012e5d3d21e
2015-09-08T15:16:00.034+0200 ERROR [main] cli.commands.Run - ERROR: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: Unable to persist node ID
  at org.graylog.collector.utils.CollectorId.<init>(CollectorId.java:43)
  at org.graylog.collector.utils.CollectorIdModule.configure(CollectorIdModule.java:25)
  while locating org.graylog.collector.utils.CollectorId

1 error
2015-09-08T15:16:00.035+0200 INFO  [main] cli.commands.Run - Exit
2015-09-08T15:16:00.036+0200 INFO  [Thread-1] cli.commands.Run - Stopping...

Thanks for help.

**Comment by joschi** [comment]
It looks like the Graylog Collector isn't able to write into the directory in which it needs to write its ID file (see https://github.com/Graylog2/collector/blob/0.4.1/config/collector.conf.example#L9-L14).

Please use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [our IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support questions about Graylog.
